spring.application.name=atividade_fixacao

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://localhost:3306/db_att_fixacao
spring.datasource.username=root
spring.datasource.password=
