spring.application.name=api_criptografada

# MySQL Database Connection URL
spring.datasource.url=jdbc:mysql://localhost:3306/db_api?useSSL=false&serverTimezone=UTC

# Database Credentials
spring.datasource.username=root
spring.datasource.password=

# MySQL Driver Class (optional in Spring Boot 2.x/3.x)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

